// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNewEM3F9wDe3p2vCcXqb8UUCOTKNvNw',
    appId: '1:341740538399:web:74388f5610b05a405ce32a',
    messagingSenderId: '341740538399',
    projectId: 'teak-banner-385707',
    authDomain: 'teak-banner-385707.firebaseapp.com',
    storageBucket: 'teak-banner-385707.appspot.com',
    measurementId: 'G-DMHSYQG6PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAucWkEXVVU7ACpnwKFE0FRgZ0FYGX9U',
    appId: '1:341740538399:android:f2ca5112f37f7d915ce32a',
    messagingSenderId: '341740538399',
    projectId: 'teak-banner-385707',
    storageBucket: 'teak-banner-385707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08O7AFGYNPyGVZMcehvHCi-72CImCzqo',
    appId: '1:341740538399:ios:35447e8dc6558e975ce32a',
    messagingSenderId: '341740538399',
    projectId: 'teak-banner-385707',
    storageBucket: 'teak-banner-385707.appspot.com',
    iosBundleId: 'com.example.millInfo',
  );
}
